# Write a function to compute 5/0 and use try/except to catch the exceptions.

In [2]:
def compute():
    return 5/0

try:
    compute()
except ZeroDivisionError:
    print("division by zero!")
finally:
    print('computed')


division by zero!
computed


# Implement a Python program to generate all sentences where subject is in ["Americans",
"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

In [3]:
subjects = ['Americans','Indains']
verbs = ['play', 'watch']
objects = ['Baseball','Cricket']

for i in subjects:
    for j in verbs:
        for k in objects:
            print(i+" "+j+" "+k)


Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indains play Baseball
Indains play Cricket
Indains watch Baseball
Indains watch Cricket


# Write a function so that the columns of the output matrix are powers of the input vector.

In [6]:
import numpy as np

## Iterate over each number in the input vector n times, n being the number of columns in the o/p matrix and output 
## an intermediate vector. Use diff order formula based on increasing and decreasing condition.
## Reshape the intermediate vector using the size of the input vector (rows) and n (columns) to generate the o/p matrix. 
   
def gen_vander_matrix(inputvector, n, increasing=False):
    
    if not increasing:
        output_matx = np.array([x**(n-1-i) for x in inputvector for i in range(n)]).reshape(inputvector.size,n)
    elif increasing:
        output_matx = np.array([x**i for x in inputvector for i in range(n)]).reshape(inputvector.size,n)
    
    return output_matx

print("------------OUTPUT-------------\n")

inputvector1 = np.array([1,2,3,4,5])
no_col_opmat = 3
op_matx_dec_order = gen_vander_matrix(inputvector1,no_col_opmat,False)
op_matx_inc_order = gen_vander_matrix(inputvector1,no_col_opmat,True)

print("The input array is:",inputvector1,"\n")
print("Number of columns in output matrix should be:",no_col_opmat,"\n")
print("Vander matrix of the input array in decreasing order of powers:\n\n",op_matx_dec_order,"\n")
print("Vander matrix of the input array in increasing order of powers:\n\n",op_matx_inc_order,"\n")

inputvector2 = np.array([1,2,4,6,8,10])
no_col_opmat = 5
op_matx_dec_order = gen_vander_matrix(inputvector2,no_col_opmat,False)
op_matx_inc_order = gen_vander_matrix(inputvector2,no_col_opmat,True)

print("---------------------------------------------------------------\n")
print("The input array is:",inputvector2,"\n")
print("Number of columns in output matrix should be:",no_col_opmat,"\n")
print("Vander matrix of the input array in decreasing order of powers:\n\n",op_matx_dec_order,"\n")
print("Vander matrix of the input array in increasing order of powers:\n\n",op_matx_inc_order,"\n")


------------OUTPUT-------------

The input array is: [1 2 3 4 5] 

Number of columns in output matrix should be: 3 

Vander matrix of the input array in decreasing order of powers:

 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]] 

Vander matrix of the input array in increasing order of powers:

 [[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]] 

---------------------------------------------------------------

The input array is: [ 1  2  4  6  8 10] 

Number of columns in output matrix should be: 5 

Vander matrix of the input array in decreasing order of powers:

 [[    1     1     1     1     1]
 [   16     8     4     2     1]
 [  256    64    16     4     1]
 [ 1296   216    36     6     1]
 [ 4096   512    64     8     1]
 [10000  1000   100    10     1]] 

Vander matrix of the input array in increasing order of powers:

 [[    1     1     1     1     1]
 [    1     2     4     8    16]
 [    1     4    16    64   256]
 [    1     6    36   216  1296]
 [ 